### ISSUE TITLE
Package installment

### ISSUE THREAD

**Issue by simonmunzert** [petermeissner/robotstxt#4]
The installment of additional pacakges (curl, digest and jsonlite in my case) collides with already installed packages:

> devtools::install_github("petermeissner/robotstxt")
Downloading GitHub repo petermeissner/robotstxt@master
Installing robotstxt
Installing 3 packages: curl, digest, jsonlite
package ‘curl’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘curl’
package ‘digest’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘digest’

**Comment by petermeissner** [comment]
Hmmm, 

I checked the package again locally, via win_build and installed it from Github without any problems. 

- have you tried updating your packages prior to installation? 
- did you install from a clean -- freshly started; no default packages loaded; no other R-sessions running -- R-session? [e.g.](http://stackoverflow.com/questions/26570912/error-in-installation-a-r-package)

**Comment by simonmunzert** [comment]
Still o R 3.2.2 and no package updates prior to the package installation, but this should not be a requirement, right?
However, after reinstalling the packages, it worked (but then see issue #3). I'm gonna try again today.

**Comment by petermeissner** [comment]
I do not get this on my Linux machine. But I get it with Windows / Rstudio ... 

**Manually install the packages that complain.**

I tried but got: 

```r
devtools::install_github("petermeissner/robotstxt")
Downloading GitHub repo petermeissner/robotstxt@master
Installing robotstxt
Installing 1 packages: digest
package ‘digest’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘digest’
"C:/PROGRA~1/R/R-32~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD  \
  INSTALL  \
  "C:/Users/Admin/AppData/Local/Temp/Rtmpm8dI2U/devtoolsb023b5415/petermeissner-robotstxt-31f0383"  \
  --library="C:/Users/Admin/Documents/R/win-library/3.2" --install-tests 
```

I did: 
```r
> install.packages("digest")
Error in install.packages : Updating loaded packages
```

RStudio did: 
```r
Restarting R session...

> install.packages("digest")
Installing package into ‘C:/Users/Admin/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/digest_0.6.9.zip'
Content type 'application/zip' length 171695 bytes (167 KB)
downloaded 167 KB

package ‘digest’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Admin\AppData\Local\Temp\RtmpCwNgJH\downloaded_packages
> devtools::install_github("petermeissner/robotstxt")
Downloading GitHub repo petermeissner/robotstxt@master
Installing robotstxt
"C:/PROGRA~1/R/R-32~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD  \
  INSTALL  \
  "C:/Users/Admin/AppData/Local/Temp/RtmpCwNgJH/devtools166c79575712/petermeissner-robotstxt-31f0383"  \
  --library="C:/Users/Admin/Documents/R/win-library/3.2" --install-tests 

* installing *source* package 'robotstxt' ...
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (robotstxt)
```

**some further thoughts**

I do not think you need R 3.2.3 to get this work. But robotstxt demands stringr (>= 1.0.0) and httr (>= 1.0.0) which are quite new and should themselves ask for newer versions of digest, jsonlite ... . What happens, I think is that digest is locked / in use by RStudio perhaps - all just guesses.
