### ISSUE TITLE
Move portion of the main README to vignette(s)

### ISSUE THREAD

**Issue by jrdnbradford** [petermeissner/robotstxt#95]
Everything below the `Usage` heading should probably be in a vignette, for instance. This is complicated by a current vignette (using_robotstxt.Rmd) that shares much of the content of the main README.

**Comment by petermeissner** [comment]
Just a comment:
The use of a long README was deliberate. 
Vignettes are a great idea, but they are much less accessible:
E.g. as far as I know, most Rusers do not know about them or it takes some time to learn that vignettes exist. 
Also, vignettes are harder to find. The README is somethingg people will always find and find first.

**Comment by jrdnbradford** [comment]
@petermeissner thanks for this input. I'll close this issue.
